spring:
  application:
    name: EXCEL-SERVICE
  config:
    import: configserver:http://${configServerHost}:${configServerPort}
eureka:
  client:
    service-url:
      default-zone: http://EUREKA-SERVER    