version: "3.1"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.1
    
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
   