eureka:
  client:
    service-url:
      default-zone: http://EUREKA-SERVER 
  
spring:
  application:
    name: GATEWAY
  config:
    import: configserver:http://${configServerHost}:${configServerPort}
 